### ISSUE TITLE
Pip 20.1 will break installation

### ISSUE THREAD

**Issue by piraz** [candango/automatoes#43]
When updating pip to 20.1 the pip install automatoes (with cache cleared) will break with this error:

```
pip install automatoes
Collecting automatoes
  Using cached automatoes-0.9.1.tar.gz (29 kB) <---- ???? the cache was cleared, anyways...
    ERROR: Command errored out with exit status 1:
     command: /root/autoenv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ueteb4ql/automatoes/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ueteb4ql/automatoes/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-xfpz_9dw
         cwd: /tmp/pip-install-ueteb4ql/automatoes/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ueteb4ql/automatoes/setup.py", line 69, in <module>
        install_requires=resolve_requires("requirements/basic.txt"),
      File "/tmp/pip-install-ueteb4ql/automatoes/setup.py", line 40, in resolve_requires
        return [str(ir.req) for ir in requirements]
      File "/tmp/pip-install-ueteb4ql/automatoes/setup.py", line 40, in <listcomp>
        return [str(ir.req) for ir in requirements]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by piraz** [comment]
We're good until 20.0.2. Downgrading to this version will be a workaround.

Setuptools isn't the issue here, the problem is with pip.

**Comment by piraz** [comment]
Here's the reference bug https://github.com/pypa/pip/issues/8188.

**Comment by szepeviktor** [comment]
`pip3 install --upgrade pip==20.0.2`

**Comment by szepeviktor** [comment]
@piraz Could you fix the version number in the title and in the top comment?

**Comment by piraz** [comment]
@szepeviktor 20.0.2 is breaking for you? Is the same error? If not could you paste the error here?

**Comment by szepeviktor** [comment]
No, v21 is breaking with the same error.

Could you change "2.1" to "21"?

**Comment by piraz** [comment]
> > 20.0.2 is breaking for you?
> 
> No, v21 is breaking with the same error.
> 
> Could you change "2.1" to "21"?

I should change to 20.1.

**Comment by szepeviktor** [comment]
Yes!

**Comment by piraz** [comment]
We got a release tonight, America/Toronto timezone.

**Comment by piraz** [comment]
The issue was introduced by https://github.com/pypa/pip/pull/7747 as parse_requirements started to return a ParsedRequirement.

This is the commit: https://github.com/pypa/pip/pull/7747/commits/f2e49b3946423c07a46398f691f721771b80b38a
This is changing the return: https://github.com/pypa/pip/pull/7747/commits/90e4eb3eedc7c550c2dd036b7a535cdec50a93d5

Basically this is decoupling parse_requirements from InstallRequirement and we need to use parsed_requirement.requirement instead of install_requirement.req. I don't know if the changed changed the install_requirement to be consistent but I don't care anymore about this.

In the future we need to resolve this by our own as pip don't want to give us a public interface to easily resolve requirements.

**Comment by szepeviktor** [comment]
> In the future we need to resolve this by our own as pip don't want to give us a public interface to easily resolve requirements.

👍

**Comment by piraz** [comment]
Maybe this: https://github.com/pypa/pip/issues/8023
